import { supabase as defaultSupabase, supabaseAdmin } from './supabase';
import type { SupabaseClient } from '@supabase/supabase-js';
import type {
  Game,
  GamePlay,
  GameLeaderboard,
  CreateGameRequest,
  UpdateGameRequest,
  SubmitGamePlayRequest,
  GameFilters,
  LeaderboardQuery,
  LeaderboardEntry,
  GameWithCreator
} from '@/types/game';

// ============================================
// ERROR HANDLING HELPER
// ============================================

const getErrorMessage = (error: unknown): string => {
  if (error instanceof Error) return error.message;
  if (typeof error === 'object' && error !== null && 'message' in error) {
    return String((error as { message: string }).message);
  }
  return 'Unknown error occurred';
};

// ============================================
// GAME CRUD OPERATIONS
// ============================================

/**
 * Create a new game
 */
export const createGame = async (
  gameData: CreateGameRequest,
  userId: string,
  supabaseClient?: SupabaseClient
): Promise<{ success: boolean; data?: Game; error?: string }> => {
  try {
    const supabase = supabaseClient || defaultSupabase;
    const { data, error } = await supabase
      .from('games')
      .insert({
        title: gameData.title,
        description: gameData.description || null,
        topic: gameData.topic,
        game_type: gameData.game_type,
        difficulty: gameData.difficulty,
        subject: gameData.subject || null,
        grade_level: gameData.grade_level || null,
        config: gameData.config,
        thumbnail_url: gameData.thumbnail_url || null,
        user_id: userId,
        is_public: gameData.is_public ?? true,
        allow_anonymous_play: gameData.allow_anonymous_play ?? true,
        share_code: '' // Will be auto-generated by trigger
      })
      .select()
      .single();

    if (error) {
      console.error('Error creating game:', error);
      return { success: false, error: getErrorMessage(error) };
    }

    // Add tags if provided
    if (gameData.tags && gameData.tags.length > 0) {
      const tagInserts = gameData.tags.map(tag => ({
        game_id: data.id,
        tag: tag,
        tag_type: 'topic'
      }));

      const { error: tagError } = await supabase
        .from('game_tags')
        .insert(tagInserts);

      if (tagError) {
        console.error('Error adding tags:', tagError);
        // Don't fail the whole operation for tag errors
      }
    }

    return { success: true, data };
  } catch (error) {
    console.error('Unexpected error creating game:', error);
    return { success: false, error: getErrorMessage(error) };
  }
};

/**
 * Get a game by ID
 */
export const getGameById = async (
  gameId: string
): Promise<{ success: boolean; data?: Game; error?: string }> => {
  try {
    const { data, error } = await defaultSupabase
      .from('games')
      .select('*')
      .eq('id', gameId)
      .single();

    if (error) {
      console.error('Error fetching game:', error);
      return { success: false, error: getErrorMessage(error) };
    }

    return { success: true, data };
  } catch (error) {
    console.error('Unexpected error fetching game:', error);
    return { success: false, error: getErrorMessage(error) };
  }
};

/**
 * Get a game by share code
 */
export const getGameByShareCode = async (
  shareCode: string
): Promise<{ success: boolean; data?: Game; error?: string }> => {
  try {
    const { data, error } = await defaultSupabase
      .from('games')
      .select('*')
      .eq('share_code', shareCode.toUpperCase())
      .eq('is_active', true)
      .single();

    if (error) {
      console.error('Error fetching game by share code:', error);
      return { success: false, error: getErrorMessage(error) };
    }

    return { success: true, data };
  } catch (error) {
    console.error('Unexpected error fetching game by share code:', error);
    return { success: false, error: getErrorMessage(error) };
  }
};

/**
 * Get user's games
 */
export const getUserGames = async (
  userId: string,
  filters?: GameFilters
): Promise<{ success: boolean; data?: Game[]; error?: string }> => {
  try {
    let query = defaultSupabase
      .from('games')
      .select('*')
      .eq('user_id', userId)
      .eq('is_active', true);

    // Apply filters
    if (filters?.game_type) {
      query = query.eq('game_type', filters.game_type);
    }
    if (filters?.difficulty) {
      query = query.eq('difficulty', filters.difficulty);
    }
    if (filters?.subject) {
      query = query.eq('subject', filters.subject);
    }

    // Sorting
    if (filters?.sort_by === 'recent') {
      query = query.order('created_at', { ascending: false });
    } else if (filters?.sort_by === 'popular') {
      query = query.order('total_plays', { ascending: false });
    } else if (filters?.sort_by === 'rating') {
      query = query.order('avg_score', { ascending: false });
    } else {
      query = query.order('created_at', { ascending: false });
    }

    // Pagination
    if (filters?.limit) {
      query = query.limit(filters.limit);
    }
    if (filters?.offset) {
      query = query.range(filters.offset, filters.offset + (filters.limit || 10) - 1);
    }

    const { data, error } = await query;

    if (error) {
      console.error('Error fetching user games:', error);
      return { success: false, error: getErrorMessage(error) };
    }

    return { success: true, data: data || [] };
  } catch (error) {
    console.error('Unexpected error fetching user games:', error);
    return { success: false, error: getErrorMessage(error) };
  }
};

/**
 * Update a game
 */
export const updateGame = async (
  gameId: string,
  updates: UpdateGameRequest
): Promise<{ success: boolean; data?: Game; error?: string }> => {
  try {
    const { data, error } = await defaultSupabase
      .from('games')
      .update(updates)
      .eq('id', gameId)
      .select()
      .single();

    if (error) {
      console.error('Error updating game:', error);
      return { success: false, error: getErrorMessage(error) };
    }

    return { success: true, data };
  } catch (error) {
    console.error('Unexpected error updating game:', error);
    return { success: false, error: getErrorMessage(error) };
  }
};

/**
 * Delete a game (soft delete)
 */
export const deleteGame = async (
  gameId: string
): Promise<{ success: boolean; error?: string }> => {
  try {
    const { error } = await defaultSupabase
      .from('games')
      .update({ is_active: false })
      .eq('id', gameId);

    if (error) {
      console.error('Error deleting game:', error);
      return { success: false, error: getErrorMessage(error) };
    }

    return { success: true };
  } catch (error) {
    console.error('Unexpected error deleting game:', error);
    return { success: false, error: getErrorMessage(error) };
  }
};

// ============================================
// GAME DISCOVERY
// ============================================

/**
 * Discover public games with filters
 */
export const discoverGames = async (
  filters?: GameFilters
): Promise<{ success: boolean; data?: GameWithCreator[]; error?: string }> => {
  try {
    // Use the helper view for public games
    let query = defaultSupabase
      .from('public_games_feed')
      .select('*');

    // Apply filters
    if (filters?.game_type) {
      query = query.eq('game_type', filters.game_type);
    }
    if (filters?.difficulty) {
      query = query.eq('difficulty', filters.difficulty);
    }
    if (filters?.subject) {
      query = query.eq('subject', filters.subject);
    }
    if (filters?.topic) {
      query = query.ilike('topic', `%${filters.topic}%`);
    }
    if (filters?.min_plays) {
      query = query.gte('total_plays', filters.min_plays);
    }
    if (filters?.is_featured) {
      query = query.eq('is_featured', true);
    }

    // Sorting
    if (filters?.sort_by === 'recent') {
      query = query.order('created_at', { ascending: false });
    } else if (filters?.sort_by === 'popular') {
      query = query.order('total_plays', { ascending: false });
    } else if (filters?.sort_by === 'rating') {
      query = query.order('avg_score', { ascending: false });
    } else {
      query = query.order('created_at', { ascending: false });
    }

    // Pagination
    if (filters?.limit) {
      query = query.limit(filters.limit);
    }
    if (filters?.offset) {
      query = query.range(filters.offset, filters.offset + (filters.limit || 20) - 1);
    }

    const { data, error } = await query;

    if (error) {
      console.error('Error discovering games:', error);
      return { success: false, error: getErrorMessage(error) };
    }

    return { success: true, data: data || [] };
  } catch (error) {
    console.error('Unexpected error discovering games:', error);
    return { success: false, error: getErrorMessage(error) };
  }
};

// ============================================
// GAME PLAY TRACKING
// ============================================

/**
 * Submit a game play result
 */
export const submitGamePlay = async (
  playData: SubmitGamePlayRequest,
  userId?: string | null,
  supabaseClient?: SupabaseClient
): Promise<{ success: boolean; data?: GamePlay; error?: string }> => {
  try {
    // Use admin client for server-side operations to bypass RLS
    // This is safe because we're on the server and data is already validated
    const supabase = supabaseAdmin || supabaseClient || defaultSupabase;
    
    const insertData = {
        game_id: playData.game_id,
        user_id: userId || null,
        player_name: playData.player_name || null,
        device_type: playData.device_type || 'web',
        time_ended: new Date().toISOString(),
        time_taken_seconds: playData.time_taken_seconds,
        completed: playData.completed,
        completion_percentage: playData.completion_percentage,
        // Quiz-specific
        points_earned: playData.points_earned || null,
        questions_correct: playData.questions_correct || null,
        questions_total: playData.questions_total || null,
        max_streak: playData.max_streak || null,
        hints_used: playData.hints_used || null,
        lives_remaining: playData.lives_remaining || null,
        // Quiz answers for review
        answers: playData.answers || null,
        // Simulation-specific
        stars_earned: playData.stars_earned || null,
        interactions_count: playData.interactions_count || null,
        // Flashcard-specific
        cards_reviewed: playData.cards_reviewed || null,
        cards_mastered: playData.cards_mastered || null,
        avg_confidence: playData.avg_confidence || null,
        // Matching-specific
        pairs_matched: playData.pairs_matched || null,
        pairs_total: playData.pairs_total || null,
        mistakes_count: playData.mistakes_count || null,
        // Feedback
        feedback_rating: playData.feedback_rating || null,
        feedback_text: playData.feedback_text || null,
        quit_reason: playData.quit_reason || null
    };
    
    const { data, error } = await supabase
      .from('game_plays')
      .insert(insertData)
      .select()
      .single();

    if (error) {
      console.error('Error submitting game play:', error);
      return { success: false, error: getErrorMessage(error) };
    }

    return { success: true, data };
  } catch (error) {
    console.error('Unexpected error submitting game play:', error);
    return { success: false, error: getErrorMessage(error) };
  }
};

/**
 * Get user's game play history
 */
export const getUserGamePlays = async (
  userId: string,
  gameId?: string
): Promise<{ success: boolean; data?: GamePlay[]; error?: string }> => {
  try {
    let query = defaultSupabase
      .from('game_plays')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false });

    if (gameId) {
      query = query.eq('game_id', gameId);
    }

    const { data, error } = await query;

    if (error) {
      console.error('Error fetching game plays:', error);
      return { success: false, error: getErrorMessage(error) };
    }

    return { success: true, data: data || [] };
  } catch (error) {
    console.error('Unexpected error fetching game plays:', error);
    return { success: false, error: getErrorMessage(error) };
  }
};

// ============================================
// LEADERBOARDS
// ============================================

/**
 * Get leaderboard for a game
 */
export const getGameLeaderboard = async (
  query: LeaderboardQuery
): Promise<{ success: boolean; data?: LeaderboardEntry[]; error?: string }> => {
  try {
    let dbQuery = defaultSupabase
      .from('game_leaderboards')
      .select(`
        *,
        users:user_id (email)
      `)
      .eq('game_id', query.game_id)
      .order('best_score', { ascending: false });

    // Pagination
    if (query.limit) {
      dbQuery = dbQuery.limit(query.limit);
    }
    if (query.offset) {
      dbQuery = dbQuery.range(query.offset, query.offset + (query.limit || 10) - 1);
    }

    const { data, error } = await dbQuery;

    if (error) {
      console.error('Error fetching leaderboard:', error);
      return { success: false, error: getErrorMessage(error) };
    }

    // Transform data to LeaderboardEntry format
    const entries: LeaderboardEntry[] = (data || []).map((entry, index) => ({
      rank: (query.offset || 0) + index + 1,
      user_id: entry.user_id,
      user_email: (entry.users as { email: string })?.email || 'Anonymous',
      best_score: entry.best_score,
      best_time_seconds: entry.best_time_seconds,
      best_accuracy: entry.best_accuracy,
      total_plays: entry.total_plays,
      perfect_score_count: entry.perfect_score_count,
      percentile: entry.percentile
    }));

    return { success: true, data: entries };
  } catch (error) {
    console.error('Unexpected error fetching leaderboard:', error);
    return { success: false, error: getErrorMessage(error) };
  }
};

/**
 * Get user's rank in a game
 */
export const getUserRank = async (
  gameId: string,
  userId: string
): Promise<{ success: boolean; data?: GameLeaderboard; error?: string }> => {
  try {
    const { data, error } = await defaultSupabase
      .from('game_leaderboards')
      .select('*')
      .eq('game_id', gameId)
      .eq('user_id', userId)
      .single();

    if (error) {
      // User might not have played yet
      if (error.code === 'PGRST116') {
        return { success: true, data: undefined };
      }
      console.error('Error fetching user rank:', error);
      return { success: false, error: getErrorMessage(error) };
    }

    return { success: true, data };
  } catch (error) {
    console.error('Unexpected error fetching user rank:', error);
    return { success: false, error: getErrorMessage(error) };
  }
};

// ============================================
// GAME LIKES
// ============================================

/**
 * Like a game
 */
export const likeGame = async (
  gameId: string,
  userId: string
): Promise<{ success: boolean; error?: string }> => {
  try {
    const { error } = await defaultSupabase
      .from('game_likes')
      .insert({
        game_id: gameId,
        user_id: userId
      });

    if (error) {
      // Already liked - ignore duplicate key error
      if (error.code === '23505') {
        return { success: true };
      }
      console.error('Error liking game:', error);
      return { success: false, error: getErrorMessage(error) };
    }

    return { success: true };
  } catch (error) {
    console.error('Unexpected error liking game:', error);
    return { success: false, error: getErrorMessage(error) };
  }
};

/**
 * Unlike a game
 */
export const unlikeGame = async (
  gameId: string,
  userId: string
): Promise<{ success: boolean; error?: string }> => {
  try {
    const { error } = await defaultSupabase
      .from('game_likes')
      .delete()
      .eq('game_id', gameId)
      .eq('user_id', userId);

    if (error) {
      console.error('Error unliking game:', error);
      return { success: false, error: getErrorMessage(error) };
    }

    return { success: true };
  } catch (error) {
    console.error('Unexpected error unliking game:', error);
    return { success: false, error: getErrorMessage(error) };
  }
};

/**
 * Check if user liked a game
 */
export const checkGameLike = async (
  gameId: string,
  userId: string
): Promise<{ success: boolean; liked: boolean; error?: string }> => {
  try {
    const { data, error } = await defaultSupabase
      .from('game_likes')
      .select('game_id')
      .eq('game_id', gameId)
      .eq('user_id', userId)
      .single();

    if (error) {
      // Not liked if not found
      if (error.code === 'PGRST116') {
        return { success: true, liked: false };
      }
      console.error('Error checking game like:', error);
      return { success: false, liked: false, error: getErrorMessage(error) };
    }

    return { success: true, liked: !!data };
  } catch (error) {
    console.error('Unexpected error checking game like:', error);
    return { success: false, liked: false, error: getErrorMessage(error) };
  }
};
